name: chaplin_cafe_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2


  get_it: ^7.6.6

  #state management
  bloc: ^8.1.2

  #compare dart object like "=="
  equatable: ^2.0.5

  #making api requests
  retrofit: ^4.0.3

  #date format
  intl: ^0.18.1

  #for api requests
  dio: ^5.4.0

  #for localization process
  easy_localization: ^3.0.3

  #A flutter library to show images from the internet and keep them in the cache directory.
  cached_network_image: ^3.3.1

  #local data storage like Android room
  floor: ^1.4.2

  #utility
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  retrofit_generator: ^8.0.6
  floor_generator: ^1.4.2


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/languages/
    - assets/lotties/

