name: chaplin_cafe_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #state management
  bloc: ^8.1.2
  provider: ^6.1.1

  flutter_bloc: ^8.1.5

  #compare dart object like "=="
  equatable: ^2.0.5

  qr_code_scanner: ^1.0.0

  #making api requests
  retrofit: ^4.0.3

  story_view: ^0.16.5

  #date format
  intl: ^0.18.1

  #for api requests
  dio: ^5.4.0

  #for dependency injection
  get_it: ^7.6.7

  #internet connection
  internet_connection_checker: ^1.0.0+1

  #for localization process
  easy_localization: ^3.0.3

  #A flutter library to show images from the internet and keep them in the cache directory.
  cached_network_image: ^3.3.1

  #local data storage like Android room
  floor: ^1.4.2

  #utility
  google_fonts: ^6.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: ^8.0.6
  floor_generator: ^1.4.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/chaplin_logo.jpeg"
  min_sdk_android: 21
  remove_alpha_ios: true
  
flutter:

  uses-material-design: true

  assets:
    - assets/languages/
    - assets/images/

